<?xml version="1.0" encoding="UTF-8"?>

<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
    <xacro:property name="base_length" value="0.6"/>
    <xacro:property name="base_width" value="${base_length * (2/3)}"/>
    <xacro:property name="base_height" value="${base_length / 3}"/>
    <xacro:property name="wheel_radius" value="${base_length / 6}"/>
    <xacro:property name="wheel_length" value="${wheel_radius / 2}"/>

    <xacro:macro name="wheel_link" params="prefix radius length">
        <link name="${prefix}_wheel_link">
            <xacro:cylinder_inertia r="${wheel_radius}" l="${wheel_length}" m="1.0" o_xyz="0.0 0.0 0.0" o_rpy="${pi / 2.0} 0.0 0.0"/>
            <visual>
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
                </geometry>
                <origin xyz="0.0 0.0 0.0" rpy="${pi / 2.0} 0.0 0.0"/>
                <material name="grey"/>
            </visual>
            <collision>
                <geometry>
                    <!-- <sphere radius="${wheel_radius}"/> -->
                    <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
                </geometry>
                <origin xyz="0.0 0.0 0.0" rpy="${pi / 2.0} 0.0 0.0"/>
            </collision>
        </link>
    </xacro:macro>

    <link name="base_footprint"></link>

    <link name="base_link">
        <xacro:box_inertia l="${base_length}" w="${base_width}" h="${base_height}" m="5.0" o_xyz="0.0 0.0 ${wheel_radius}" o_rpy="0.0 0.0 0.0"/>
        <visual>
            <geometry>
                <box size="${base_length} ${base_width} ${base_height}"/>
            </geometry>
            <origin xyz="0.0 0.0 ${base_height/2}" rpy="0.0 0.0 0.0"/>
            <material name="blue"/>
        </visual>
        <collision>
            <geometry>
                <box size="${base_length} ${base_width} ${base_height}"/>
            </geometry>
            <origin xyz="0.0 0.0 ${base_height/2}" rpy="0.0 0.0 0.0"/>
        </collision>
    </link>

    <xacro:wheel_link prefix="right" radius="${wheel_radius}" length="${wheel_length}"/>
    <xacro:wheel_link prefix="left" radius="${wheel_radius}" length="${wheel_length}"/>


    <link name="caster_wheel_link">
        <xacro:sphere_inertia r="${wheel_radius/2}" m="0.5" o_xyz="0.0 0.0 0.0" o_rpy="0.0 0.0 0.0"/>
        <visual>
            <geometry>
                <sphere radius="${wheel_radius / 2}"/>
            </geometry>
            <origin xyz="0.0 0.0 0.0" rpy="0 0.0 0.0"/>
            <material name="grey"/>
        </visual>
        <collision>
            <geometry>
                <sphere radius="${wheel_radius / 2}"/>
            </geometry>
            <origin xyz="0.0 0.0 0.0" rpy="0 0.0 0.0"/>
        </collision>
    </link>

    <joint name="footprint_to_base_joint" type="fixed">
        <parent link="base_footprint"/>
        <child link="base_link"/>
        <origin xyz="0.0 0.0 ${wheel_radius}" rpy="0.0 0.0 0.0"/>

    </joint>

    <joint name="base_to_right_wheel" type="continuous">
        <parent link="base_link"/>
        <child link="right_wheel_link"/>
        <origin xyz="${-base_length / 4} -0.225 0.0" rpy="0.0 0.0 0.0"/>
        <axis xyz="0.0 1.0 0.0"/>
    </joint>

    <joint name="base_to_left_wheel" type="continuous">
        <parent link="base_link"/>
        <child link="left_wheel_link"/>
        <origin xyz="${-base_length / 4} 0.225 0.0" rpy="0.0 0.0 0.0"/>
        <axis xyz="0.0 1.0 0.0"/>
    </joint>

    <joint name="base_to_caster_wheel" type="fixed">
        <parent link="base_link"/>
        <child link="caster_wheel_link"/>
        <origin xyz="${base_length / 3} 0.0 -0.05" rpy="0.0 0.0 0.0"/>
        <axis xyz="0.0 1.0 0.0"/>
    </joint>

</robot>